# Generated by Django 3.0.7 on 2020-07-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulationApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectInfo',
            new_name='Project',
        ),
    ]
